spring:
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:mysql://localhost:3306/chaegmanbo?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: newseung7!


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false


aladin:
  url:
    item_search: http://www.aladin.co.kr/ttb/api/ItemSearch.aspx
    item_list: http://www.aladin.co.kr/ttb/api/ItemList.aspx
    item_lookup:  http://www.aladin.co.kr/ttb/api/ItemLookUp.aspx
  client:
    TTBKey: ttbkmimi05281551001
